INSERT OR IGNORE INTO verticals (slug, number, title, body, status, image_url, display_order, is_published) VALUES
('flow-exclusive', '01', 'Flow Exclusive',
 'Marketing, sales, and collections outsourcing on an exclusive basis for projects that need an acceleration in their cashflows.',
 'Ongoing Projects',
 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1000&q=80&auto=format&fit=crop',
 10, 1),
('terra-by-flow', '02', 'Terra by Flow',
 'Empowering developers with a 360 degree online way of sales and marketing for Plotted Developments.',
 'Ongoing Projects',
 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1000&q=80&auto=format&fit=crop',
 20, 1),
('flow-luxe', '03', 'Flow Luxe',
 'Boutique luxury retail service designed to provide international-standard realtor services to HNI home buyers.',
 'Coming Soon',
 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1000&q=80&auto=format&fit=crop',
 30, 1),
('flow-manage', '04', 'Flow Manage',
 'An end-to-end DM solution for land owners or young developers wanting to outsource their entire value chain from product planning to construction management.',
 'Coming Soon',
 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1000&q=80&auto=format&fit=crop',
 40, 1);
